### ISSUE TITLE
Linking

### ISSUE THREAD

**Issue by textbrowser** [maandree/libkeccak#1]
In order to complete the test binary, I need to change the location of libkeccak.

diff --git a/Makefile b/Makefile
index fce64ae..cf4a92c 100644
--- a/Makefile
+++ b/Makefile
@@ -103,7 +103,7 @@ bin/libkeccak.a: $(foreach O,$(LIB_OBJ),obj/libkeccak/$(O).o
 test: bin/test
 
 bin/test: obj/test.o bin/libkeccak.so bin/libkeccak.so.$(LIB_MAJOR) bin/libkecc
-       $(CC) $(FLAGS) -Lbin -lkeccak -o $@ $< $(LDFLAGS)
+       $(CC) $(FLAGS) -Lbin -o $@ $< $(LDFLAGS) -lkeccak
 
 obj/test.o: src/test.c src/libkeccak/*.h src/libkeccak.h
        @mkdir -p obj

**Comment by maandree** [comment]
What do you have in $(CC) and $(LDFLAGS)?

**Comment by textbrowser** [comment]
$(CC) expands to cc and $(LDFLAGS) is empty. cc is a symbolic link to gcc.

**Comment by maandree** [comment]
That's weird. What did the compiler say when `-lkeccak` was between `-Lbin` and `-o $@`?

**Comment by textbrowser** [comment]
The usual "undefined reference" errors.

test.c:(.text.startup+0x1d90): undefined reference to `libkeccak_generalised_sum_fd'

**Comment by textbrowser** [comment]
Do you have libkeccak installed in your system?

**Comment by maandree** [comment]
Yes, but it still builds if I uninstall it.
It really should not better it -l flags are before or after -o and the object files.

Does it build for you if the line is
```
$(CC) $(FLAGS) -o $@ $< -Lbin -lkeccak $(LDFLAGS)
```

**Comment by maandree** [comment]
Do you need to do the same change if you run `make benchmark`?

**Comment by textbrowser** [comment]
Yes, to both. The location of libkeccak is important.

**Comment by maandree** [comment]
Then I'll change it to `$(CC) $(FLAGS) -o $@ $< -Lbin -lkeccak $(LDFLAGS)`.
It is important that `-lkeccak` is before `$(LDFLAGS)` otherwise `$(LDFLAGS)` can cause problems during linking,
