### ISSUE TITLE
Where in the world?

### ISSUE THREAD

**Issue by textbrowser** [maandree/libkeccak#2]
Could you add a fancy option where one could trace the origins of all of the output bits? Like, where in the data source did the first bit originate from? Or, what happened to the first bit in the input? So, let's say it's a zero. Did it become a one or remain a zero and where in the world is it? You can assume that the input size is the same as the output size.

**Comment by maandree** [comment]
Sorry, way too complex and not generally useful (should not be done in a library), but it might (perhaps) be useful as a didactic tool. It might be fun (but I am not going to do this) to right a library that should be used to do thing for any hash.

**Comment by textbrowser** [comment]
Alright.

**Comment by gvanas** [comment]
FYI, [KeccakTools](https://github.com/gvanas/KeccakTools) could help you on this.

Kind regards,
Gilles

**Comment by textbrowser** [comment]
Cool. Thank you.
