### ISSUE TITLE
libkeccak.h unusable from C++: cast from void

### ISSUE THREAD

**Issue by thiagomacieira** [maandree/libkeccak#20]
If you remove all the `restrict` (#19), libkeccak.h still doesn't compile in C++ mode:
```
/usr/include/libkeccak.h: In function ‘libkeccak_hmac_state* libkeccak_hmac_create(const libkeccak_spec*, const void*, size_t)’:
/usr/include/libkeccak.h:909:61: error: invalid conversion from ‘void*’ to ‘libkeccak_hmac_state*’ [-fpermissive]
  909 |         struct libkeccak_hmac_state *restrict state = malloc(sizeof(struct libkeccak_hmac_state));
      |                                                       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             |
      |                                                             void*
/usr/include/libkeccak.h: In function ‘libkeccak_hmac_state* libkeccak_hmac_duplicate(const libkeccak_hmac_state*)’:
/usr/include/libkeccak.h:1035:60: error: invalid conversion from ‘void*’ to ‘libkeccak_hmac_state*’ [-fpermissive]
 1035 |         struct libkeccak_hmac_state *restrict dest = malloc(sizeof(struct libkeccak_hmac_state));
      |                                                      ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                            |
      |                                                            void*
/usr/include/libkeccak.h: In function ‘size_t libkeccak_hmac_marshal(const libkeccak_hmac_state*, void*)’:
/usr/include/libkeccak.h:1054:40: error: invalid conversion from ‘void*’ to ‘unsigned char*’ [-fpermissive]
 1054 |         unsigned char *restrict data = data_;
      |                                        ^~~~~
      |                                        |
      |                                        void*
```

It's also missing the `extern "C"` wrapper around all functions.

**Comment by maandree** [comment]
This is not a C++ project, so I'm not going to deteriorate the code to fix these issues.

A simple solution is to just copy–paste the functions prototypes, structs and macro into your project, and add “extern "C"“ around it. Of course, you would have to remove the keywords `restrict` and `inline`.

**Comment by thiagomacieira** [comment]
I'm not asking you to change your library to C++ or to make your sources compile as C++.

However, it's good practice to allow C++ users to use your library. Right now, they can't.

Besides removing the offending `restrict`, all you'd need to do is insert casts, which in C would be no-op. For example:
```c
 struct libkeccak_hmac_state * state = (struct libkeccak_hmac_state *)malloc(sizeof(struct libkeccak_hmac_state));
```

**Comment by maandree** [comment]
You are asking me to write polyglot code that impose restrictions and make to code
look worse, even if it, in this case isn't that big of a deal, in other cases it is worse.
I'm really not interested in participating in some practice of writing polyglot code
when the proper solutions are (1) write C++ wrapper conforming to C++ coding
practices, (2) use a tool that converts a C header file to a C++ header file (by
removing the keywords restrict and auto, replace new, delete and any other
C++-keyword with non-keywords, add “extern "C"”, and make inline functions,
non-inline), or (3) that compilers or C++ makes it possible to include C files that
are parsed as C rather than C++. I don't think it is too much to ask that C++ users
do what everyone else using a programming language that is not a superset of C
does, or that compiler developers do that for them.

**Comment by dangelog** [comment]
Would you accept a patch for this? I don't think it's going to be invasive at all:

* wrap in extern C (6 lines of code or so)
* use a `#define` for restrict (just in the header)
* implement the 3-4 functions calling `malloc` in a .c file, i.e. out of line.

**Comment by thiagomacieira** [comment]
I'm asking that you do the standard practice of writing header files that are both C and C++. This has done by >99% of C library projects for over 30 years.

Your option (1) is not practical: one *can't* write a C++ wrapper to your C library because they can't use the library in the first place, without copy & paste & modify. That would mean keeping two copies of all constants and structures, and all function declarations. This is what we're trying to avoid.

Your option (2) is not reasonable because such a tool doesn't exist. Like I said, >99% of C libraries simply write code that is compatible with both C and C++.

For the same reason, your option (3) is even more unreasonable, because it requires an even greater effort.

**Comment by maandree** [comment]
For option (1), you just need to copy and paste, and remove stuff as previously discussed, and add “extern "C"”, so far this is basically no work. Then, in the case of libkeccak, you only need to keep up with additions, and that's only if you have any interest in them. The only time you would actually need to make changes is when major number in the libraries version number changes, as this is what makes backwards-compatibility breakage, and I doing my best not to ever break backwards compatibility. Of course, in the future, there could be some struct that when used must be accompanied with a size or version parameter (or include it as a field in the struct), and that would “require” keeping up to date, but in the case libkeccak I don't think that will ever happen. Doing this (that is, mainly, removing the “inline” keyword and function bodies) is enough to be able to use the library from C++, and then you can make a proper C++ version.

Option (2) is a general solution, and that would be a nice tool to have. For libkeccak, you can always use
`sed -e '/^{/,/^}/a;' -e '/-legacy.h/d' -e 's/\(inline\|register\|restrict\)//g' | sed '/^{/,/^}/d'`

**Comment by maandree** [comment]
> Would you accept a patch for this? I don't think it's going to be invasive at all:
> 
> * wrap in extern C (6 lines of code or so)
> * use a `#define` for restrict (just in the header)
> * implement the 3-4 functions calling `malloc` in a .c file, i.e. out of line.

No, but I could make a C++ version of libkeccak.

I would like to write a replacement and deal with things I'm unhappy about with libkeccak. And I could make a C++ version for that one.
