### ISSUE TITLE
README erroneously mentions libsha2

### ISSUE THREAD

**Issue by BenWiederhake** [maandree/libkeccak#4]
I'm not sure whether that's supposed to be libsha3 instead, or just is completely wrong, so sorry for the lack of a PR.

**Comment by maandree** [comment]
The mention is correct.

**Comment by BenWiederhake** [comment]
How?  I grepped the entire repository after a build, and none of the files mention any kind of `sha2`.

**Comment by BenWiederhake** [comment]
... I'm stupid.  In all seriousness, I didn't notice that it says "SEE ALSO".  Now I feel stupid.
