### ISSUE TITLE
Fails to build with Clang

### ISSUE THREAD

**Issue by wjmelements** [maandree/libkeccak#9]
From the output of `make`:
```
ar rc libkeccak.a libkeccak/digest.o libkeccak/files.o libkeccak/generalised-spec.o libkeccak/hex.o libkeccak/state.o libkeccak/mac/hmac.o
ar -s libkeccak.a
cc -shared -Wl,-soname,libkeccak.so.1 -o libkeccak.so libkeccak/digest.o libkeccak/files.o libkeccak/generalised-spec.o libkeccak/hex.o libkeccak/state.o libkeccak/mac/hmac.o -s
ld: warning: option -s is obsolete and being ignored
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libkeccak.so] Error 1
```

```
$ cc --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
$ uname -a
Darwin Williams-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

**Comment by wjmelements** [comment]
The macOS equivalent of `.so` is `.dylib` iirc

**Comment by maandree** [comment]
See https://github.com/maandree/libkeccak/blob/master/Makefile#L7-L12

**Comment by wjmelements** [comment]
How easy is it to create a condition so the makefile doesn't have to be modified?

**Comment by maandree** [comment]
It's very easy, but I want my Makefiles to be as portable as possible and POSIX make does not support such things.

**Comment by cloudwizard** [comment]
It is fine to require modification but I suggest adding a line to the README.  It would save a lot of searching.  Thanks

**Comment by zbeekman** [comment]
A formula has been submitted to Mac Homebrew for libkeccak (with the eventual intention of including sha3sum, I believe). However, there is a problem with your macOS fix: it should be `$(LIB_MAJOR).$(LIB_EXT)` on macOS, e.g., `libqhull.7.2.0.dylib` not `libqhull.dylib.7.2.0`. I gather that POSIX makefiles do not have functions like GNU make does, so maybe there needs to be a variable to specify the SO name?

**Comment by maandree** [comment]
Should work with `make install OSCONFIGFILE=macos.mk` now.

**Comment by zbeekman** [comment]
I can confirm that this compiles & installs correctly now. A PR for this was opened in Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/pull/36905

It needs a better test; the current test only includes a header and doesn't link anything. I may try to find time later (this weekend) to fix this up. If anyone wants to send me a patch, that would allow me to get to it sooner.
